---
version: '3.3'

services:
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    env_file: .env
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    env_file:
      - .env
      - .env.development
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
