---
development:
  adapter: mysql2
  database: <%= ENV.fetch('MYSQL_DATABASE', 'reu_dev') %>
  username: <%= ENV.fetch('MYSQL_USER', 'root') %>
  password: <%= ENV.fetch('MYSQL_PASSWORD', 'testing123') %>
  host: <%= ENV.fetch('MYSQL_HOST', '127.0.0.1') %>
  port: <%= ENV.fetch('MYSQL_PORT', '3306') %>
  pool: 5
  timeout: 5000

test:
  adapter: mysql2
  database: <%= ENV.fetch('MYSQL_TEST_DATABASE', 'reu_test') %>
  username: <%= ENV.fetch('MYSQL_USER', 'root') %>
  password: <%= ENV.fetch('MYSQL_PASSWORD', 'testing123') %>
  host: <%= ENV.fetch('MYSQL_HOST', '127.0.0.1') %>
  port: <%= ENV.fetch('MYSQL_PORT', '3306') %>
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  database: reu_mstp_surf_new__prod
  username:
  password:
  pool: 5
  timeout: 5000


old:
  adapter: mysql2
  database: reu_mstp_surf_development
  username: root
  password:
  host: localhost

old_production:
  adapter: mysql2
  database: reu_mstp_surf_production
  encoding: utf8
  username: reu_mstp_surf
  password: sqz_EIz_EIpEojbeY4EojIMg
  host: localhost
