
development:
  adapter: mysql2
  database: reum_sdni_dev
  username: root
  pool: 5
  timeout: 5000

test:
  adapter: mysql2
  database: reum_sdni_test
  username: root
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  database: reu_sdni_prod
  username:
  password:
  pool: 5
  timeout: 5000
