# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'

development:
  adapter: mysql2
  database: reumanager_demo_dev
  username: root
  pool: 5
  timeout: 5000

test:
  adapter: mysql2
  database: reumanager_demo_test
  username: root
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  database: reumanager_demo_prod
  username:
  password:
  pool: 5
  timeout: 5000
