# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
login: &login
  adapter: mysql2
  username: root
  password:
  socket: /tmp/mysql.sock
  pool: 5
  timeout: 5000

development:
  <<: *login
  database: reumanager_demo_dev

test:
  <<: *login
  database: reumanager_demo_test

production:
  <<: *login
  database: reumanager_demo_prod
