general_description:
  name: general_description
  description: This is the text used as a general description for your program.
    It is displayed on the front page under the main image.
  value: |
    <p>Interested in pursuing a graduate study or career in Ocean Science? Our National Science Foundation funded Fall Research Experiences for Undergraduates (NSF-REU) Program is an ideal start to your journey. This internship will provide you with an essential experience of research in oceanography, marine science, and atmospheric sciences, along with access to a state-of-the-art ocean science research facility with well-equipped lab spaces.</p>

    <p>You will carry out an independent research project under the expert supervision of BIOS scientists and  undertake training in scientific communication, research methods and ethics, and career development. You  will give presentations about your research to your peers and colleagues at BIOS. Our program offers the  opportunity to take part in various field excursions to learn about Bermuda’s natural history, and all  students will have the opportunity to participate in an oceanographic research cruise aboard our research   vessel the R/V Atlantic Explorer.</p>
highlights:
  name: highlights
  description: ''
  value: |
    <ul>
      <li>$500 weekly stipend and return airfare</li>
      <li>On-campus housing and all meals</li>
      <li>Weekly seminars and workshops</li>
      <li>Gain invaluable research experience and knowledge in field and laboratory techniques from world-renowned BIOS scientists</li>
      <li>Field and boat excursions to explore the local flora, fauna, and waters of Bermuda</li>
    </ul>
eligibility_requirements:
  name: eligibility_requirements
  description: ''
  value: |
    <ul>
      <li> This internship program is funded by the U.S. National Science Foundation (NSF) and is open only to United States Citizens or U.S. Permanent Residents</li>
      <li> Students who have completed at least one year of undergraduate study and have not graduated at the time of the program are eligible</li>
      <li> Underrepresented groups and students attending colleges or universities with limited STEM research opportunities are particularly encouraged to apply</li>
      <li> Applicants are ineligible if they have participated in a prior NSF-REU in Ocean Sciences</li>
      <li> This is a 12-week program offered in the Fall (Aug-Nov)</li>
      <li> Return airfare, campus accommodation, meals and a competitive stipend are covered by the BIOS REU program; medical/travel insurance is the responsibility of the student</li>
      <li> Students must commit to the entire program (no late arrivals or early departures)</li>
      <li> Successful candidates are encouraged to arrange for independent study credit through their home institutions</li>
    </ul>
application_information:
  name: application_information
  description: ''
  value: |
    <ul>
      <li>Fill out the application questions, including personal statement descriptions of your experience, contact information for two people who will provide recommendations, and indication of the mentors and projects within our program that are of interest to you.</li>
      <li>Upload your academic transcript(s) from all undergraduate institutions you have attended. Please do not upload password-protected documents.</li>
      <li>Those providing recommendations for you must upload their letters themselves.</li>
    </ul>
acknowledgment_of_funding_soruces:
  name: acknowledgment_of_funding_soruces
  description: Please provide text to be included on the site as acknowledgment of program funding. In addition (or instead) you may send an image of the funding agency logo.
  value: |
    The REU program is funded by the National Science Foundation. We acknowledge partnership from the SETI Institute, from the CAMPARE program at California State University, and from NASA.
submit_application_heading:
  name: submit_application_heading
  description: ''
  value: |
ready_to_submit_message:
  name: ready_to_submit_message
  description: ''
  value: |
