general_description:
  name: general_description
  description: This is the text used as a general description for your program.
    It is displayed on the front page under the main image.
  value: |
    <p>The SETI Institute (<a href="https://www.seti.org">www.seti.org</a>), a non-profit private scientific research institution located in California’s Silicon Valley, invites you to apply for a summer Research Experience for Undergraduates program for highly motivated students interested in astronomy, astrobiology, and planetary science research. You will work with scientists at the SETI Institute and at the nearby NASA Ames Research Center on projects spanning the field of astrobiology from microbiology to observational astronomy.</p>
    <p>The program includes a week-long field trip including a collaborative project at the SETI Institute’s Allen Telescope Array, located at the Hat Creek Radio Astronomy Observatory in Northern California, as well as a field experience studying hydrothermal systems at nearby Lassen Volcanic National Park. Students will also participate in local field trips to places such as historic Lick Observatory and the NASA Ames Wind Tunnel facility and other nearby locations of scientific interest, and attend seminars, lectures, and discussions on astronomy, astrobiology, and planetary science. Students will live in dormitory housing at the NASA Ames Research Center. At the end of the summer, students will give presentations on their research projects, and many projects will be selected for submission to a national scientific conference, which the selected students will be funded to attend.</p>
highlights:
  name: highlights
  description: ''
  value: |
    <p>Astronomy and the Search for Extraterrestrial Intelligence (SETI), including but not limited to</p>
    <ul>
      <li>Planetary formation</li>
      <li>SETI and radio astronomy</li>
      <li>Extrasolar planets</li>
    </ul>
    <p>Planetary Science and the Search for Life in the Solar System, including but not limited to</p>
    <ul>
      <li>Saturn’s rings</li>
      <li>Mars geomorphology and spectroscopy</li>
      <li>Survival of microbes under extreme conditions</li>
    </ul>
eligibility_requirements:
  name: eligibility_requirements
  description: ''
  value: |
    <ul>
      <li>Full-time undergraduate student</li>
      <li>U.S. citizen or U.S. permanent resident (i.e., green card)</li>
      <li> Has completed sophomore year before the summer of the internship</li>
      <li> Will still be an undergraduate during the fall term following the summer of the internship</li>
    </ul>
application_information:
  name: application_information
  description: ''
  value: |
    <ul>
      <li>Fill out the application questions, including personal statement descriptions of your experience, contact information for two people who will provide recommendations, and indication of the mentors and projects within our program that are of interest to you.</li>
      <li>Upload your academic transcript(s) from all undergraduate institutions you have attended. Please do not upload password-protected documents.</li>
      <li>Those providing recommendations for you must upload their letters themselves.</li>
    </ul>
acknowledgment_of_funding_soruces:
  name: acknowledgment_of_funding_soruces
  description: Please provide text to be included on the site as acknowledgment of program funding. In addition (or instead) you may send an image of the funding agency logo.
  value: |
    The REU program is funded by the National Science Foundation. We acknowledge partnership from the SETI Institute, from the CAMPARE program at California State University, and from NASA.
