general_description:
  name: general_description
  description: This is the text used as a general description for your program.
    It is displayed on the front page under the main image.
  value: |
    General Description\n\nThe National Science Foundation's Research Experience for Undergraduates (NSF-REU) program provides undergraduate students access to state-of-the-art facilities, the opportunity to work with accomplished and experienced faculty mentors, and to participate in highly collaborative, cutting-edge research projects.

highlights:
  name: highlights
  description: ''
  value: |
    <ul>
      <li>$XXXX stipend</li>
      <li>Reimbursement of travel costs up to $XXX</li>
      <li>On-campus housing and a meal/dining plan - Hands-on research experience</li>
      <li>Weekly seminars and workshops</li>
      <li>Training in scientific communication</li>
    </ul>
eligibility_requirements:
  name: eligibility_requirements
  description: ''
  value: |
    <ul>
      <li>United States citizens or U.S. permanent residents</li>
      <li>Enrolled in a undergraduate institute for the duration of the program</li>
      <li>Must commit to the entire program (no late arrivals, no early departures)</li>
      <li>Not available to graduating seniors</li>
    </ul>
application_information:
  name: application_information
  description: ''
  value: |
    <ul>
      <li>A completed application form, which includes a personal statement, any honors and awards received, and any scholarly </li>
      <li>Unofficial transcripts of all previous college or university work, including work in progress</li>
      <li>Contact information for 2 references (preferably professors in your major field) who know you well and can attest for your scholastic abilities</li>
      <li>Once you begin an application, you can check the status at any time by logging into this website</li>
      <li>Only applications completed by the deadline will be reviewed</li>
    </ul>
acknowledgment_of_funding_soruces:
  name: acknowledgment_of_funding_soruces
  description: Please provide text to be included on the site as acknowledgment of program funding. In addition (or instead) you may send an image of the funding agency logo.
  value: Demo program is supported by ...
