general_description:
  name: general_description
  description: This is the text used as a general description for your program.
    It is displayed on the front page under the main image.
  value: |
    The National Science Foundation's Research Experience for Undergraduates (NSF-REU) program provides undergraduate students access to state-of-the-art facilities, the opportunity to work with accomplished and experienced faculty mentors, and to participate in highly collaborative, cutting-edge research projects.

highlights:
  name: highlights
  description: ''
  value: |
    <ul>
      <li>$5,000 stipend plus $350 food allowance</li>
      <li>On-campus housing or housing allowance</li>
      <li>Travel to and from San Diego</li>
      <li>Hands-on research experience</li>
      <li>Weekly research development workshops</li>
      <li>GRE preparation course</li>
      <li>Field trips and social events</li>
    </ul>
eligibility_requirements:
  name: eligibility_requirements
  description: ''
  value: |
    <ul>
      <li>Full-time undergraduate student</li>
      <li>U.S. citizen or permanent resident</li>
    </ul>
application_information:
  name: application_information
  description: ''
  value: |
    <ul>
      <li>Major components of the online application include: a personal statement, a copy of your unofficial school transcript (as a pdf), and contact information for one reference</li>
      <li>The person writing your letter of recommendation will be contacted via e-mail and will submit their letter online</li>
      <li>Once you begin an application, you can check the status of it any time by logging into this website</li>
      <li>Only complete applications will be reviewed</li>
    </ul>
acknowledgment_of_funding_soruces:
  name: acknowledgment_of_funding_soruces
  description: Please provide text to be included on the site as acknowledgment of program funding. In addition (or instead) you may send an image of the funding agency logo.
  value: This program is supported by the National Science Foundation.
