general_description:
  name: general_description
  description: This is the text used as a general description for your program.
    It is displayed on the front page under the main image.
  value: |
    <p>Interested in pursuing a graduate study or career in Ocean Science? Our National Science Foundation funded Fall Research Experiences for Undergraduates (NSF-REU) Program is an ideal start to your journey. This internship will provide you with an essential experience of research in oceanography, marine science, and atmospheric sciences, along with access to a state-of-the-art ocean science research facility with well-equipped lab spaces.</p>

    <p>You will carry out an independent research project under the expert supervision of BIOS scientists and  undertake training in scientific communication, research methods and ethics, and career development. You  will give presentations about your research to your peers and colleagues at BIOS. Our program offers the  opportunity to take part in various field excursions to learn about Bermuda’s natural history, and all  students will have the opportunity to participate in an oceanographic research cruise aboard our research   vessel the R/V Atlantic Explorer.</p>
highlights:
  name: highlights
  description: ''
  value: |
    <p>Astronomy and the Search for Extraterrestrial Intelligence (SETI), including but not limited to</p>
    <ul>
      <li>Planetary formation</li>
      <li>SETI and radio astronomy</li>
      <li>Extrasolar planets</li>
    </ul>
    <p>Planetary Science and the Search for Life in the Solar System, including but not limited to</p>
    <ul>
      <li>Saturn’s rings</li>
      <li>Mars geomorphology and spectroscopy</li>
      <li>Survival of microbes under extreme conditions</li>
    </ul>
eligibility_requirements:
  name: eligibility_requirements
  description: ''
  value: |
    <ul>
      <li>U.S. citizen or U.S. permanent resident (i.e., green card)</li>
      <li>Full-time undergraduate student</li>
      <ul>
        <li> Has completed sophomore year before the summer of the internship</li>
        <li> Will still be an undergraduate during the fall term following the summer of the internship</li>
      </ul>
    </ul>
application_information:
  name: application_information
  description: ''
  value: |
    <ol>
      <li>Current resume.</li>
      <li>Copies of current university or college transcripts.</li>
      <li>Two letters of recommendation. Your letters should be from people competent to judge your potential for research, such as college/university professors or research project advisors, who are familiar with your academic and research accomplishments.</li>
    </ol>

    <ul>
      <li>You will be asked to complete four long-answer questions.</li>
      <li>You will be asked to list the top three BIOS mentors with whom you would like to work. Please take time to review the faculty research descriptions and the list of Mentors and Potential Research Projects on the BIOS website.</li>
      <li>Once you begin an application, you can check the status at any time by logging into this website.</li>
      <li>Only applications completed by the deadline will be reviewed.</li>
    </ul>
acknowledgment_of_funding_soruces:
  name: acknowledgment_of_funding_soruces
  description: Please provide text to be included on the site as acknowledgment of program funding. In addition (or instead) you may send an image of the funding agency logo.
  value: |
    The REU program is funded by the National Science Foundation. We acknowledge partnership from the SETI Institute, from the CAMPARE program at California State University, and from NASA.
submit_application_heading:
  name: submit_application_heading
  description: ''
  value: |
ready_to_submit_message:
  name: ready_to_submit_message
  description: ''
  value: |
